name: "Weekly Mods Update"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update-mods:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.5"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate output.json
        run: |
          python main.py --mods-url https://mods-guerra.netlify.app/mods.json --output output.json --send-telegram

      - name: Upload output.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: mods-output
          path: output.json
