name: "Weekly Mods Update"

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update-mods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.5"

      - name: Install dependencies
        run: |
          pip install requests colorama

      - name: Generate output.json
        run: |
          python mod_updater.py --mods-url https://mods-guerra.netlify.app/mods.json --output output.json

      - name: Upload output.json artifact
        uses: actions/upload-artifact@v3
        with:
          name: mods-output
          path: output.json
