name: "Weekly Mods Update"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # Every day at 12:00 UTC

permissions:
  contents: write

jobs:
  update-mods:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.5"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate output.json
        run: |
          python main.py --mods-url https://mods-guerra.netlify.app/mods.json --full-output -o output.json

      - name: Upload output.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: mods-output
          path: output.json

      - name: Commit and Push updated output.json
        run: |
          git config user.name "jesewescience[bot]"
          git config user.email "jesewescience[bot]@users.noreply.github.com"
          git add output.json
          git commit -m "Auto-update output.json [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
